### ISSUE TITLE
Mentioning Onboarding

### ISSUE THREAD

**Issue by DEAD1nsane** [Hacksore/discord-md#4]
# How to mention:
![SmartSelect_20241013_031103_Discord](https://github.com/user-attachments/assets/56a25419-5b12-402d-b29e-cde7ebfd3dc8)
![SmartSelect_20241013_031112_Discord](https://github.com/user-attachments/assets/52a6c4b9-5202-4239-b087-5359c5230072)

---

> [!TIP]
> `<id:home>`, `<id:browse>`, `<id:customize>`

> [!IMPORTANT]
> <details>
> <summary>here is what they do & how they look</summary>
> 
> ![SmartSelect_20241013_033534_Discord](https://github.com/user-attachments/assets/a03a3b6a-f870-4665-a562-d81956a952c2)
![SmartSelect_20241013_033506_Discord](https://github.com/user-attachments/assets/2332f93f-fa57-49e7-ad43-7bfa7d1394ce)
![SmartSelect_20241013_033615_Discord](https://github.com/user-attachments/assets/6842bfa0-ce49-4bc6-8cbe-f07e8a36174a)
</details>

> [!NOTE]
> <details>
> <summary></summary>
> 
> Not sure if it would be best under `Mention` or maybe it's own category that's upto you. but I thought you should be aware of these and so should the public.
</details>

**Comment by Hacksore** [comment]
I added them here but didn't put the icons yet, for now at least it shows the concept.

https://discord-md.vercel.app/feature/misc

**Comment by DEAD1nsane** [comment]
very nice :)
